-- schema.sql

-- Garante que as tabelas sejam criadas do zero, se já existirem
DROP TABLE IF EXISTS contem, emprestimo, exemplar, livro, aluno CASCADE;

-- Tabela de Alunos
CREATE TABLE aluno (
    matricula BIGINT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    curso VARCHAR(255) NOT NULL
);

-- Tabela de Livros
CREATE TABLE livro (
    codigo BIGINT PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    autor VARCHAR(255) NOT NULL,
    editora VARCHAR(255) NOT NULL,
    ano_pub INT NOT NULL
);

-- Tabela de Exemplares
CREATE TABLE exemplar (
    tombo BIGINT PRIMARY KEY,
    codigo_livro BIGINT NOT NULL,
    CONSTRAINT fk_livro
        FOREIGN KEY(codigo_livro) 
        REFERENCES livro(codigo)
);

-- Tabela de Empréstimos
CREATE TABLE emprestimo (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    mat_aluno BIGINT NOT NULL,
    data_emprestimo DATE NOT NULL,
    previsao_devolucao DATE,
    dias_atraso INT,
    CONSTRAINT fk_aluno
        FOREIGN KEY(mat_aluno) 
        REFERENCES aluno(matricula)
);

-- Tabela Associativa 'contem' (Emprestimo-Exemplar)
CREATE TABLE contem (
    id_emp BIGINT NOT NULL,
    tombo_emp BIGINT NOT NULL,
    data_devol DATE,
    CONSTRAINT fk_emprestimo
        FOREIGN KEY(id_emp) 
        REFERENCES emprestimo(id),
    CONSTRAINT fk_exemplar
        FOREIGN KEY(tombo_emp) 
        REFERENCES exemplar(tombo),
    PRIMARY KEY (id_emp, tombo_emp)
);

-- Mensagem de sucesso
\echo 'Tabelas criadas com sucesso!'